name: Update Global News

on:
  schedule:
    - cron: '0 */4 * * *' # هر ۴ ساعت یکبار
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run script
        run: python main.py
        
      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Updated world news" || echo "No changes to commit"
          git push origin main

