name: Update Global Magazine

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser requests beautifulsoup4 jdatetime pytz

      - name: Run Global Scraper
        run: python global_news.py # مطمئن شوید نام فایل پایتون در مخزن همین است

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update News" || exit 0
          git push
